{{- if .Values.backend.sqllite.enabled  }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mlflow.fullname" . }}-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.sqllite.storage }}
{{- end }}